// src/components/EquipmentCard/EquipmentCard.jsx
// ── Nexleaf Design System — EquipmentCard (mobile list card) ──────────────────
// On mobile, table-heavy equipment lists become cards. Each card shows only the
// decision-critical fields and keeps the distinct status dimensions clearly
// separated (Health / Maintenance / Lifecycle) — never a copy of every desktop
// column. The whole card is tappable and routes to the record (tertiary) page.
//
//   <EquipmentCard
//     name="Vestfrost MK 144" type="Vaccine Freezer"
//     serial="DCM-2024-001" facility="Mombasa"
//     health="functional" maintenance="upcoming" lifecycle="approaching decommissioning"
//     onClick={() => goTo(id)} />

import { useState } from 'react';
import { StatusBadge } from '../Badge/Badge.jsx';
import { Skeleton } from '../Skeleton/Skeleton.jsx';
import {
  TEXT_DEFAULT, TEXT_SUBDUED, BORDER_DEFAULT,
  COLOR_PRIMARY, COLOR_PRIMARY_HOVER_SHADOW, BG_SURFACE, BG_SURFACE_ACTIVE,
} from '../../tokens/index.js';

const IcoChevron = ({ color = TEXT_SUBDUED }) => (
  <svg width={18} height={18} viewBox="0 0 20 20" fill="none" aria-hidden="true">
    <path d="M7.5 5l5 5-5 5" stroke={color} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
  </svg>
);

const IcoFridge = ({ color = TEXT_SUBDUED }) => (
  <svg width={22} height={22} viewBox="0 0 24 24" fill="none" aria-hidden="true">
    <rect x="6" y="3" width="12" height="18" rx="2" stroke={color} strokeWidth="1.5" />
    <path d="M6 10h12M9 6v2M9 13v3" stroke={color} strokeWidth="1.5" strokeLinecap="round" />
  </svg>
);

const IcoPin = ({ color = TEXT_SUBDUED }) => (
  <svg width={14} height={14} viewBox="0 0 20 20" fill="none" aria-hidden="true">
    <path d="M10 17s5-4.5 5-9a5 5 0 1 0-10 0c0 4.5 5 9 5 9Z" stroke={color} strokeWidth="1.4" strokeLinejoin="round" />
    <circle cx="10" cy="8" r="1.6" stroke={color} strokeWidth="1.4" />
  </svg>
);

// Shared card container styles (used by both the data card and the skeleton),
// so the loading placeholder is the same shape/size and the list never reflows.
const cardShell = {
  display: 'flex', gap: 12, alignItems: 'flex-start', width: '100%',
  padding: 12, background: BG_SURFACE, borderRadius: 8,
  fontFamily: 'Inter, sans-serif', boxSizing: 'border-box',
};

export function EquipmentCard({
  name,
  type,
  serial,
  facility,
  image,
  icon,
  health,
  maintenance,
  lifecycle,
  onClick,
  ariaLabel,
  // Render a shape-matching skeleton in place of the content (list still loading).
  loading = false,
  // Force the interactive look in docs: 'default' | 'hover'.
  state = 'default',
}) {
  const [hover, setHover] = useState(false);
  const interactive = typeof onClick === 'function';

  if (loading) {
    return (
      <div style={{ ...cardShell, border: `1px solid ${BORDER_DEFAULT}` }} aria-busy="true" aria-label="Loading equipment">
        <Skeleton width={48} height={48} radius={8} ariaLabel="Loading equipment" />
        <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 8, paddingTop: 2 }}>
          <Skeleton width="60%" height={12} ariaLabel={null} />
          <Skeleton width="85%" height={11} ariaLabel={null} />
          <Skeleton width="45%" height={11} ariaLabel={null} />
          <div style={{ display: 'flex', gap: 6, marginTop: 2 }}>
            <Skeleton width={70} height={18} radius={100} ariaLabel={null} />
            <Skeleton width={58} height={18} radius={100} ariaLabel={null} />
          </div>
        </div>
      </div>
    );
  }

  // Hover ring shows on real hover (interactive) or when forced via `state`.
  const showHover = state === 'hover' || (hover && interactive);

  return (
    <div
      role={interactive ? 'button' : undefined}
      tabIndex={interactive ? 0 : undefined}
      aria-label={ariaLabel || name}
      onClick={onClick}
      onKeyDown={interactive ? (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onClick(); } } : undefined}
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        ...cardShell,
        border: `1px solid ${showHover ? COLOR_PRIMARY : BORDER_DEFAULT}`,
        boxShadow: showHover ? `0 0 0 1px ${COLOR_PRIMARY_HOVER_SHADOW}` : 'none',
        cursor: interactive ? 'pointer' : 'default', textAlign: 'left',
        transition: 'border-color 0.15s, box-shadow 0.15s',
      }}
    >
      {/* Thumbnail */}
      <div style={{
        width: 48, height: 48, borderRadius: 8, flexShrink: 0, overflow: 'hidden',
        background: BG_SURFACE_ACTIVE, display: 'flex', alignItems: 'center', justifyContent: 'center',
      }}>
        {image
          ? <img src={image} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
          : (icon || <IcoFridge />)}
      </div>

      {/* Content */}
      <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 4 }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 8 }}>
          <span style={{
            flex: 1, minWidth: 0, fontSize: 14, fontWeight: 650, color: TEXT_DEFAULT,
            overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
          }}>
            {name}
          </span>
          {interactive && <span style={{ flexShrink: 0, marginTop: 1 }}><IcoChevron /></span>}
        </div>

        {(type || serial) && (
          <span style={{
            fontSize: 13, fontWeight: 450, color: TEXT_SUBDUED,
            overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
          }}>
            {[type, serial].filter(Boolean).join(' · ')}
          </span>
        )}

        {facility && (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 13, fontWeight: 450, color: TEXT_SUBDUED }}>
            <IcoPin /> {facility}
          </span>
        )}

        {/* Status dimensions — clearly separated, text + color (never color alone) */}
        {(health || maintenance || lifecycle) && (
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 2 }}>
            {health && <StatusBadge status={health} />}
            {maintenance && <StatusBadge status={maintenance} />}
            {lifecycle && <StatusBadge status={lifecycle} />}
          </div>
        )}
      </div>
    </div>
  );
}

// angular/projects/nexleaf-angular/src/lib/equipment-card/equipment-card.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';

/** status → { tone, label } (mirrors STATUS_BADGE_MAP in React). */
const STATUS_MAP: Record<string, { tone: string; label: string }> = {
  functional: { tone: 'success', label: 'Functional' },
  active: { tone: 'success', label: 'Active' },
  faulty: { tone: 'critical', label: 'Faulty' },
  unknown: { tone: 'default', label: 'Unknown' },
  decommissioned: { tone: 'warning', label: 'Decommissioned' },
  'under maintenance': { tone: 'info', label: 'Under Maintenance' },
  'under-maintenance': { tone: 'info', label: 'Under Maintenance' },
  upcoming: { tone: 'attention', label: 'Upcoming' },
  overdue: { tone: 'critical', label: 'Overdue' },
  'approaching decommissioning': { tone: 'warning', label: 'Approaching Decommissioning' },
  'approaching-decommissioning': { tone: 'warning', label: 'Approaching Decommissioning' },
};

/**
 * nx-equipment-card — mobile list card for an equipment record.
 *
 * Shows only decision-critical fields and keeps Health / Maintenance / Lifecycle
 * as separate text badges. The whole card is tappable and routes to the record
 * page. Project a thumbnail into the `[thumb]` slot (or rely on the fallback).
 *
 *   <nx-equipment-card name="Vestfrost MK 144" type="Vaccine Freezer"
 *     serial="DCM-2024-001" facility="Mombasa" health="functional"
 *     maintenance="upcoming" (cardClick)="go(id)"></nx-equipment-card>
 */
@Component({
  selector: 'nx-equipment-card',
  standalone: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <!-- Loading: shape-matching skeleton in the same card shell (no reflow). -->
    <div class="nx-equipment-card" *ngIf="loading" aria-busy="true" aria-label="Loading equipment">
      <span class="nx-skeleton" style="width:48px;height:48px;border-radius:8px"></span>
      <div class="nx-equipment-card__body" style="gap:8px;padding-top:2px">
        <span class="nx-skeleton" style="width:60%;height:12px"></span>
        <span class="nx-skeleton" style="width:85%;height:11px"></span>
        <span class="nx-skeleton" style="width:45%;height:11px"></span>
        <div class="nx-equipment-card__statuses">
          <span class="nx-skeleton" style="width:70px;height:18px;border-radius:100px"></span>
          <span class="nx-skeleton" style="width:58px;height:18px;border-radius:100px"></span>
        </div>
      </div>
    </div>

    <div
      *ngIf="!loading"
      class="nx-equipment-card"
      [class.nx-equipment-card--interactive]="interactive"
      [class.nx-equipment-card--hover]="state === 'hover'"
      [attr.role]="interactive ? 'button' : null"
      [attr.tabindex]="interactive ? 0 : null"
      [attr.aria-label]="ariaLabel || name"
      (click)="interactive && cardClick.emit()"
      (keydown.enter)="interactive && cardClick.emit()"
      (keydown.space)="interactive && cardClick.emit()"
    >
      <div class="nx-equipment-card__thumb">
        <img *ngIf="image; else thumbSlot" [src]="image" alt="" />
        <ng-template #thumbSlot><ng-content select="[thumb]"></ng-content></ng-template>
      </div>

      <div class="nx-equipment-card__body">
        <div class="nx-equipment-card__name-row">
          <span class="nx-equipment-card__name">{{ name }}</span>
          <svg *ngIf="interactive" class="nx-equipment-card__chevron" width="18" height="18" viewBox="0 0 20 20" fill="none" aria-hidden="true">
            <path d="M7.5 5l5 5-5 5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </div>

        <span class="nx-equipment-card__meta" *ngIf="type || serial">{{ metaLine }}</span>
        <span class="nx-equipment-card__facility" *ngIf="facility">{{ facility }}</span>

        <div class="nx-equipment-card__statuses" *ngIf="health || maintenance || lifecycle">
          <span class="nx-badge" [ngClass]="'nx-badge--' + tone(health)" *ngIf="health">{{ label(health) }}</span>
          <span class="nx-badge" [ngClass]="'nx-badge--' + tone(maintenance)" *ngIf="maintenance">{{ label(maintenance) }}</span>
          <span class="nx-badge" [ngClass]="'nx-badge--' + tone(lifecycle)" *ngIf="lifecycle">{{ label(lifecycle) }}</span>
        </div>
      </div>
    </div>
  `,
})
export class NxEquipmentCardComponent {
  @Input() name?: string;
  @Input() type?: string;
  @Input() serial?: string;
  @Input() facility?: string;
  @Input() image?: string;
  @Input() health?: string;
  @Input() maintenance?: string;
  @Input() lifecycle?: string;
  @Input() ariaLabel?: string;
  /** Whole-card tap → record page (adds chevron + hover ring). */
  @Input() interactive = true;
  /** Render a shape-matching skeleton in place of the content. */
  @Input() loading = false;
  /** Force the interactive look in docs: 'default' | 'hover'. */
  @Input() state: 'default' | 'hover' = 'default';

  @Output() cardClick = new EventEmitter<void>();

  get metaLine(): string {
    return [this.type, this.serial].filter(Boolean).join(' · ');
  }

  tone(status?: string): string {
    return (status && STATUS_MAP[status.toLowerCase()]?.tone) || 'default';
  }
  label(status?: string): string {
    if (!status) return '';
    return STATUS_MAP[status.toLowerCase()]?.label || status;
  }
}
