// angular/projects/nexleaf-angular/src/lib/tertiary-actions/tertiary-actions.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { NxSheetAction } from '../bottom-sheet/bottom-sheet.component';

export interface NxTertiaryConfig {
  primary: NxSheetAction;
  more: NxSheetAction[];
}

/** Canonical state → { primary, more } map (mirrors TERTIARY_ACTION_MAP in React). */
export const NX_TERTIARY_ACTION_MAP: Record<string, NxTertiaryConfig> = {
  functional: {
    primary: { id: 'edit', label: 'Edit Information' },
    more: [
      { id: 'view-summary', label: 'View Summary' },
      { id: 'create-service-request', label: 'Create Service Request' },
      { id: 'view-plot', label: 'View Plot' },
      { id: 'view-daily-summary', label: 'View Daily Summary' },
      { id: 'assign-qr', label: 'Assign QR Code' },
    ],
  },
  faulty: {
    primary: { id: 'create-service-request', label: 'Create Service Request' },
    more: [
      { id: 'edit', label: 'Edit Information' },
      { id: 'view-open-issues', label: 'View Open Issues' },
      { id: 'view-plot', label: 'View Plot' },
      { id: 'view-daily-summary', label: 'View Daily Summary' },
      { id: 'assign-qr', label: 'Assign QR Code' },
    ],
  },
  unknown: {
    primary: { id: 'view-monitoring-issue', label: 'View Monitoring Issue' },
    more: [
      { id: 'edit', label: 'Edit Information' },
      { id: 'create-service-request', label: 'Create Service Request' },
      { id: 'view-plot', label: 'View Plot' },
      { id: 'view-daily-summary', label: 'View Daily Summary' },
      { id: 'assign-qr', label: 'Assign QR Code' },
    ],
  },
  decommissioning: {
    primary: { id: 'review-decommissioning', label: 'Review Decommissioning' },
    more: [
      { id: 'edit', label: 'Edit Information' },
      { id: 'create-service-request', label: 'Create Service Request' },
      { id: 'view-history', label: 'View History' },
      { id: 'export-record', label: 'Export Record' },
    ],
  },
};

function resolveState(state?: string): string {
  const key = String(state ?? '').toLowerCase();
  if (key === 'active') return 'functional';
  if (key === 'decommissioned' || key.indexOf('approaching') === 0) return 'decommissioning';
  return NX_TERTIARY_ACTION_MAP[key] ? key : 'functional';
}

/**
 * nx-tertiary-actions — state-driven [Primary][More] record actions.
 *
 * The primary action follows equipment state (never hardcoded to Edit). On
 * mobile, More opens nx-bottom-sheet; on desktop, an inline dropdown menu.
 *
 *   <nx-tertiary-actions state="faulty" [mobile]="isMobile"
 *     (action)="route($event)"></nx-tertiary-actions>
 */
@Component({
  selector: 'nx-tertiary-actions',
  standalone: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="nx-tertiary-actions" [class.nx-tertiary-actions--full]="fullWidth">
      <button
        type="button"
        class="nx-btn nx-btn--primary"
        [class.nx-btn--full]="fullWidth"
        [class.nx-btn--lg]="mobile"
        (click)="action.emit(config.primary.id)"
      >{{ config.primary.label }}</button>

      <ng-container *ngIf="mobile; else desktopMore">
        <button
          type="button"
          class="nx-btn nx-btn--secondary nx-btn--lg"
          [class.nx-btn--full]="fullWidth"
          (click)="sheetOpen = true"
        >{{ moreLabel }}</button>
        <nx-bottom-sheet
          [open]="sheetOpen"
          title="Actions"
          [actions]="config.more"
          (selected)="onMore($event)"
          (closed)="sheetOpen = false"
        ></nx-bottom-sheet>
      </ng-container>

      <ng-template #desktopMore>
        <div style="position: relative; display: inline-flex;">
          <button
            type="button"
            class="nx-btn nx-btn--secondary nx-btn--disclosure"
            aria-haspopup="menu"
            [attr.aria-expanded]="menuOpen"
            (click)="menuOpen = !menuOpen"
          >{{ moreLabel }}</button>
          <div
            class="nx-tertiary-actions__menu"
            role="menu"
            *ngIf="menuOpen"
            style="position: absolute; top: calc(100% + 6px); right: 0; z-index: var(--nx-z-overlay); background: var(--nx-bg-surface); border: 1px solid var(--nx-border-default); border-radius: var(--nx-radius-sm); box-shadow: var(--nx-shadow-overlay);"
          >
            <button
              *ngFor="let a of config.more"
              type="button"
              role="menuitem"
              class="nx-tertiary-actions__menu-item"
              [class.nx-tertiary-actions__menu-item--destructive]="a.destructive"
              (click)="onMore(a.id || a.label)"
            >{{ a.label }}</button>
          </div>
        </div>
      </ng-template>
    </div>
  `,
})
export class NxTertiaryActionsComponent {
  @Input() state?: string;
  @Input() mobile = false;
  @Input() moreLabel = 'More';
  @Input() fullWidth = false;

  /** Fires with the action id for the primary and any More item. */
  @Output() action = new EventEmitter<string>();

  sheetOpen = false;
  menuOpen = false;

  get config(): NxTertiaryConfig {
    return NX_TERTIARY_ACTION_MAP[resolveState(this.state)];
  }

  onMore(id: string): void {
    this.action.emit(id);
    this.menuOpen = false;
    this.sheetOpen = false;
  }
}

// src/components/TertiaryActions/TertiaryActions.jsx
// ── Nexleaf Design System — TertiaryActions (state-driven record actions) ─────
// The action pattern for a tertiary (record/detail) page. Renders exactly two
// controls — a contextual PRIMARY action + a MORE button. The primary action is
// driven by equipment state (never hardcoded to Edit Information): when the
// equipment has an issue, the primary guides the user toward resolving it.
//
//   Functional      → Edit Information
//   Faulty          → Create Service Request
//   Unknown         → View Monitoring Issue
//   Decommissioning → Review Decommissioning
//
// On mobile, More opens a BottomSheet; on desktop/wide tablet, a Popover menu.
//
//   <TertiaryActions state="faulty" onAction={(id) => route(id)} />

import { useRef, useState } from 'react';
import { Btn } from '../Btn/Btn.jsx';
import { BottomSheet } from '../BottomSheet/BottomSheet.jsx';
import { Popover } from '../Popover/Popover.jsx';
import { useIsMobile } from '../../foundation/useViewport.js';
import { TEXT_DEFAULT, COLOR_CRITICAL, BG_HOVER } from '../../tokens/index.js';

const A = (id, label, extra) => ({ id, label, ...extra });

// Canonical state → { primary, more } map. The single source of truth for which
// action leads on a record page and what overflows into More.
export const TERTIARY_ACTION_MAP = {
  functional: {
    primary: A('edit', 'Edit Information'),
    more: [
      A('view-summary', 'View Summary'),
      A('create-service-request', 'Create Service Request'),
      A('view-plot', 'View Plot'),
      A('view-daily-summary', 'View Daily Summary'),
      A('assign-qr', 'Assign QR Code'),
    ],
  },
  faulty: {
    primary: A('create-service-request', 'Create Service Request'),
    more: [
      A('edit', 'Edit Information'),
      A('view-open-issues', 'View Open Issues'),
      A('view-plot', 'View Plot'),
      A('view-daily-summary', 'View Daily Summary'),
      A('assign-qr', 'Assign QR Code'),
    ],
  },
  unknown: {
    primary: A('view-monitoring-issue', 'View Monitoring Issue'),
    more: [
      A('edit', 'Edit Information'),
      A('create-service-request', 'Create Service Request'),
      A('view-plot', 'View Plot'),
      A('view-daily-summary', 'View Daily Summary'),
      A('assign-qr', 'Assign QR Code'),
    ],
  },
  decommissioning: {
    primary: A('review-decommissioning', 'Review Decommissioning'),
    more: [
      A('edit', 'Edit Information'),
      A('create-service-request', 'Create Service Request'),
      A('view-history', 'View History'),
      A('export-record', 'Export Record'),
    ],
  },
};

// Normalize a few aliases onto the four canonical states.
function resolveState(state) {
  const key = String(state ?? '').toLowerCase();
  if (key === 'active') return 'functional';
  if (key === 'approaching decommissioning' || key === 'approaching-decommissioning' || key === 'decommissioned') return 'decommissioning';
  return TERTIARY_ACTION_MAP[key] ? key : 'functional';
}

/** Returns { primary, more } for a given equipment state (no rendering). */
export function getTertiaryActions(state) {
  return TERTIARY_ACTION_MAP[resolveState(state)];
}

// Desktop Popover menu row.
function MenuRow({ label, destructive, onClick }) {
  return (
    <button
      type="button"
      role="menuitem"
      onClick={onClick}
      onMouseEnter={(e) => { e.currentTarget.style.background = BG_HOVER; }}
      onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}
      style={{
        display: 'flex', alignItems: 'center', width: '100%', minHeight: 40,
        padding: '8px 12px', background: 'transparent', border: 'none', cursor: 'pointer',
        textAlign: 'left', fontFamily: 'Inter, sans-serif', fontSize: 14, fontWeight: 500,
        color: destructive ? COLOR_CRITICAL : TEXT_DEFAULT, borderRadius: 6,
      }}
    >
      {label}
    </button>
  );
}

export function TertiaryActions({
  state,
  onAction,
  mobile,                 // override; defaults to useIsMobile()
  moreLabel = 'More',
  primaryVariant = 'primary',
  groups,                 // optional grouped more-actions for the mobile sheet
  fullWidth,              // override; off by default (compact, like desktop)
}) {
  const autoMobile = useIsMobile();
  const isMobile = mobile ?? autoMobile;
  const cfg = getTertiaryActions(state);

  const [sheetOpen, setSheetOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const moreRef = useRef(null);

  const fire = (id) => { onAction?.(id); };
  // Compact by default at every size — the SAME [Primary][More ▾] pair as
  // desktop; mobile only differs by the taller `large` touch height. Callers
  // can still opt into full-width by passing `fullWidth`.
  const stretch = fullWidth ?? false;

  return (
    <div style={{ display: 'flex', gap: 8, width: stretch ? '100%' : undefined }}>
      <Btn
        variant={primaryVariant}
        fullWidth={stretch}
        size={isMobile ? 'large' : 'medium'}
        onClick={() => fire(cfg.primary.id)}
      >
        {cfg.primary.label}
      </Btn>

      {isMobile ? (
        <>
          <Btn variant="secondary" fullWidth={stretch} size="large" disclosure onClick={() => setSheetOpen(true)}>
            {moreLabel}
          </Btn>
          <BottomSheet
            open={sheetOpen}
            onClose={() => setSheetOpen(false)}
            title="Actions"
            groups={groups
              ? groups.map((g) => ({ ...g, actions: g.actions.map((a) => ({ ...a, onClick: () => fire(a.id) })) }))
              : undefined}
            actions={groups ? undefined : cfg.more.map((a) => ({ ...a, onClick: () => fire(a.id) }))}
          />
        </>
      ) : (
        <>
          <span ref={moreRef} style={{ display: 'inline-flex' }}>
            <Btn variant="secondary" disclosure onClick={() => setMenuOpen((o) => !o)}>
              {moreLabel}
            </Btn>
          </span>
          <Popover
            open={menuOpen}
            onClose={() => setMenuOpen(false)}
            anchorRef={moreRef}
            placement="bottom-end"
            role="menu"
            ariaLabel="More actions"
          >
            <div style={{ padding: 4, minWidth: 220 }}>
              {cfg.more.map((a) => (
                <MenuRow
                  key={a.id}
                  label={a.label}
                  destructive={a.destructive}
                  onClick={() => { setMenuOpen(false); fire(a.id); }}
                />
              ))}
            </div>
          </Popover>
        </>
      )}
    </div>
  );
}
